[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

[functions.generate-image]
  timeout = 60
  included_files = ["node_modules/@supabase/supabase-js/**/*"]

[functions.replicate-webhook]
  timeout = 30
  included_files = ["node_modules/@supabase/supabase-js/**/*"]

[functions.test-endpoint]
  timeout = 60

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  targetPort = 5173