[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[functions.generate-image]
  timeout = 120

[functions.test-endpoint]
  timeout = 120

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/.netlify/functions/websocket-handler"
  to = "/.netlify/functions/websocket-handler"
  status = 200
  force = true
  [redirects.headers]
    Connection = "Upgrade"
    Upgrade = "websocket"
