[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  framework = "vite"

[build.environment]
  NODE_VERSION = "18.x"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@supabase/supabase-js",
    "@supabase/postgrest-js",
    "@supabase/realtime-js",
    "@supabase/storage-js"
  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
