// promptData.ts
export const subjects = [
  "research facility",
  "soap bubbles",
  "butterfly wing scales",
  "cave art",
  "structural steel",
  "topographical map",
  "porcelain",
  "quantum processor",
  "bronze artifacts",
  "cellular structures",
  "desert compound",
  "mineral formations",
  "urban infrastructure",
  "weaving machines",
  "glass sculpture",
  "skyscraper systems",
  "ceramic installation",
  "plant cells",
  "kinetic sculpture",
  "coral reef",
  "satellite arrays",
  "crystal gardens",
  "oceanic vents",
  "neural networks",
  "ancient temples",
  "wind turbines",
  "volcanic formations",
  "space stations",
  "frozen lakes",
  "digital circuits",
  "abandoned factories",
  "bacterial colonies",
  "sand dunes",
  "historic aqueducts",
  "neon installations",
  "mountain ranges",
  "fungi networks",
  "aerospace engine",
  "tide pools",
  "cloud formations",
];

export const styles = [
  "brutalist",
  "experimental",
  "generative",
  "paleolithic",
  "industrial",
  "abstract",
  "ultra-high-end",
  "technical",
  "archaeological",
  "microscopic",
  "modernist",
  "crystalline",
  "documentary",
  "contemporary",
  "sustainable",
  "minimalist",
  "futuristic",
  "organic",
  "geometric",
  "dystopian",
  "holographic",
  "molecular",
  "atmospheric",
  "biomechanical",
  "hyperrealistic",
  "deconstructivist",
];

export const techniques = [
  "architectural photography",
  "macro photography",
  "electron microscope",
  "scientific visualization",
  "medium format photography",
  "lithograph",
  "product photography",
  "technical illustration",
  "underwater photography",
  "pattern design",
  "aerial photography",
  "double exposure",
  "long exposure",
  "split-level",
  "experimental photography",
  "photogrammetry",
  "infrared imaging",
  "x-ray crystallography",
  "time-lapse",
  "thermal imaging",
  "high-speed capture",
  "light painting",
  "focus stacking",
  "satellite imaging",
  "holography",
  "microscopy",
  "3D scanning",
  "spectral imaging",
  "polarized light",
  "computational photography",
];

export const lighting = [
  "golden hour",
  "studio",
  "museum",
  "natural diffused",
  "dramatic side",
  "professional technical",
  "architectural",
  "documentary-style",
  "dramatic shadows",
  "volumetric",
  "twilight",
  "multiple color gels",
  "ambient occlusion",
  "bioluminescent",
  "blacklight",
  "fiber optic",
  "laser",
  "moonlit",
  "neon",
  "northern lights",
  "quantum dots",
  "ring light",
  "strobe",
  "subsurface scatter",
  "ultraviolet",
  "x-ray fluorescence",
];

export const characteristics = [
  "geometric concrete forms",
  "iridescent surfaces",
  "intricate repeating motifs",
  "bioluminescent elements",
  "morning fog effects",
  "hand-drawn textures",
  "translucent qualities",
  "holographic aesthetics",
  "marine biofouling details",
  "organic flowing forms",
  "interlocking volumes",
  "grainy film texture",
  "rainbow caustics",
  "polished surfaces",
  "dramatic reflections",
  "crystalline structures",
  "dendritic patterns",
  "electromagnetic fields",
  "fractal geometries",
  "gravitational lensing",
  "interference patterns",
  "liquid crystals",
  "magnetic domains",
  "nanoscale textures",
  "phase transitions",
  "plasma formations",
  "quantum interference",
  "resonance patterns",
  "supersymmetry",
  "wave functions",
];

export const perspectives = [
  "tilt-shift",
  "extreme macro",
  "atmospheric",
  "bird's eye",
  "submersible",
  "overhead",
  "worm's eye",
  "cross-section",
  "low angle",
  "split-level",
  "isometric",
  "microscopic",
  "orbital",
  "panoramic",
  "satellite",
  "stereoscopic",
  "telescopic",
  "topological",
  "x-ray",
];
