// promptData.ts
export const subjects = [
  "research facility",
  "soap bubbles",
  "butterfly wing scales",
  "cave art",
  "structural steel",
  "topographical map",
  "porcelain",
  "quantum processor",
  "bronze artifacts",
  "cellular structures",
  "desert compound",
  "mineral formations",
  "urban infrastructure",
  "weaving machines",
  "glass sculpture",
  "skyscraper systems",
  "ceramic installation",
  "plant cells",
  "kinetic sculpture",
  "coral reef",
];

export const styles = [
  "brutalist",
  "experimental",
  "generative",
  "paleolithic",
  "industrial",
  "abstract",
  "ultra-high-end",
  "technical",
  "archaeological",
  "microscopic",
  "modernist",
  "crystalline",
  "documentary",
  "contemporary",
  "sustainable",
  "minimalist",
];

export const techniques = [
  "architectural photography",
  "macro photography",
  "electron microscope",
  "scientific visualization",
  "medium format",
  "lithograph",
  "product photography",
  "technical illustration",
  "underwater photography",
  "pattern design",
  "aerial photography",
  "double exposure",
  "long exposure",
  "split-level",
  "experimental photography",
];

export const lighting = [
  "golden hour",
  "studio",
  "museum",
  "natural diffused",
  "dramatic side",
  "professional technical",
  "architectural",
  "documentary-style",
  "dramatic shadows",
  "volumetric",
  "twilight",
  "multiple color gels",
  "ambient occlusion",
];

export const characteristics = [
  "geometric concrete forms",
  "iridescent surfaces",
  "intricate repeating motifs",
  "bioluminescent elements",
  "morning fog effects",
  "hand-drawn textures",
  "translucent qualities",
  "holographic aesthetics",
  "marine biofouling details",
  "organic flowing forms",
  "interlocking volumes",
  "grainy film texture",
  "rainbow caustics",
  "polished surfaces",
  "dramatic reflections",
];

export const perspectives = [
  "tilt-shift",
  "extreme macro",
  "atmospheric",
  "bird's eye",
  "submersible",
  "overhead",
  "worm's eye",
  "cross-section",
  "low angle",
  "split-level",
];
